@startuml
title 基于GitHub的实验管理平台--类图

class users{
    +user_id（用户ID）:int
    +name（姓名）:String
    +gitbub_username（gitbub用户名）:String
    +update_date（用户gitbub帐号修改日期）:date
    +password（密码）:String
    +disable（用户是否禁用）:String
    
}

class teachers{
    +teacher_id（老师工号）:String
    +department（老师所属部门）:String
}

class students{
    +student_id（学号）:String
    +class（班级）:String
    +result_sum（成绩汇总）:int
    +course_name（专业）:String
}

users <|- students
users <|-- teachers

class grades{
    +student_id（学号）:String
    +test_id（实验编号）:int
    +standard（评分标准）：String
    +result（分数）:String
    +memo（评价）:String
    +update_date（批改日期）:date
}

class tests{
    +test_id（实验编号）:int
    +title（实验名称）:String
    +summary（概述）:String
    +update_date（批改日期）:date
    +teacher_name（老师姓名）:String
    +course_name（课程名称）:String
}

students "1" -- "n"  grades
tests "1" -- "n"  grades
tests "n" -- "1" courses
tests "n" -- "1" teachers

class courses{
    +course_id（课程ID）:String
    +course_name（课程名称）:String
    +summary（概述）:String
    +teacher_name（老师姓名）:String
}

students "1" -- "n"  courses

@enduml